SELECT NAME, GRADE, MARKS
FROM STUDENTS JOIN GRADES on MARKS between MIN_MARK and MAX_MARk
WHERE GRADE >= 8
ORDER BY GRADE desc, Name;
SELECT NULL, GRADE, MARKS
FROM STUDENTS JOIN GRADES on MARKS between MIN_MARK and MAX_MARk
WHERE GRADE < 8
ORDER BY GRADE desc, MARKS;